<a href="https://colab.research.google.com/github/sidjohal/ML_implemented/blob/main/2.%20data%20preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
    import numpy as np, pandas as pd, matplotlib.pyplot as plt

# Data preprocessing

## 1. Feature extraction

    DictVectorizer - converts dict -> matrix
    FeatureHasher - optimal for large datasets

In [ ]:
from sklearn.feature_extraction import DictVectorizer, FeatureHasher

In [ ]:
data = [{'age': 4, 'height':96.0},
{'age': 1, 'height':73.9},
{'age': 3, 'height':88.9},
{'age': 2, 'height':81.6}]

In [ ]:
dv = DictVectorizer(sparse=False)
dv.fit_transform(data)

array([[ 4. , 96. ],
       [ 1. , 73.9],
       [ 3. , 88.9],
       [ 2. , 81.6]])

In [ ]:
fh = FeatureHasher(n_features=2)
fh.transform(data).toarray()

array([[  0. , 100. ],
       [  0. ,  74.9],
       [  0. ,  91.9],
       [  0. ,  83.6]])

## 2. Data cleaning

### Feature imputation

    SimpleImputer
    KNNImputer

In [ ]:
from sklearn.impute import SimpleImputer, KNNImputer

In [ ]:
x = np.array([[7, 1], [np.nan, 8], [2, np.nan], [9, 6]])
x

array([[ 7.,  1.],
       [nan,  8.],
       [ 2., nan],
       [ 9.,  6.]])

In [ ]:
si = SimpleImputer(strategy='mean')

In [ ]:
si.fit_transform(x)

array([[7., 1.],
       [6., 8.],
       [2., 5.],
       [9., 6.]])

In [ ]:
ops = ['mean', 'median', 'most_frequent', 'constant']
for i in ops:
    print(SimpleImputer(strategy=i).fit_transform(x), i, "\n")

[[7. 1.]
 [6. 8.]
 [2. 5.]
 [9. 6.]] mean 

[[7. 1.]
 [7. 8.]
 [2. 6.]
 [9. 6.]] median 

[[7. 1.]
 [2. 8.]
 [2. 1.]
 [9. 6.]] most_frequent 

[[7. 1.]
 [0. 8.]
 [2. 0.]
 [9. 6.]] constant 



In [ ]:
kim = KNNImputer(n_neighbors=2)

In [ ]:
kim.fit_transform(x)

array([[7. , 1. ],
       [8. , 8. ],
       [2. , 3.5],
       [9. , 6. ]])

In [ ]:
xt = SimpleImputer().fit_transform(x)
xt

array([[7., 1.],
       [6., 8.],
       [2., 5.],
       [9., 6.]])

### Categorical transformers

    OneHotEncoder; OrdinalEncoder;  LabelEncoder
    LabelBinarizer; MultiLabelBinarizer

In [ ]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [ ]:
arr = np.array([1,2,1,4,2,5])
arr.reshape(-1,1), arr # -1 or length of arr

(array([[1],
        [2],
        [1],
        [4],
        [2],
        [5]]), array([1, 2, 1, 4, 2, 5]))

In [ ]:
ohe = OneHotEncoder(sparse=False)
ohe.fit_transform(arr.reshape(-1,1))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.array([1,2,1,4,2,5]).reshape(len(arr),1)

array([[1],
       [2],
       [1],
       [4],
       [2],
       [5]])

In [ ]:
OrdinalEncoder().fit_transform(x.reshape(-1,1))

array([[ 3.],
       [ 0.],
       [nan],
       [ 4.],
       [ 1.],
       [nan],
       [ 5.],
       [ 2.]])

In [ ]:
ohe.fit_transform(x)

array([[0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0.]])

In [ ]:
oe = OrdinalEncoder()
xoe = oe.fit_transform(x)
print(x, "\n\n", xoe)

[[ 7.  1.]
 [nan  8.]
 [ 2. nan]
 [ 9.  6.]] 

 [[ 1.  0.]
 [nan  2.]
 [ 0. nan]
 [ 2.  1.]]


In [ ]:
y = [1,3,2,5,2,2]
le = LabelEncoder()
le.fit_transform(y) #works

array([0, 2, 1, 3, 1, 1])

### Numerical transformers

    StandardScaler; MinMaxScaler; MaxAbsScaler
    FunctionTransformer
    PolynomialFeatures (polynomial transformation)

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

In [ ]:
x

array([[ 7.,  1.],
       [nan,  8.],
       [ 2., nan],
       [ 9.,  6.]])

In [ ]:
StandardScaler().fit_transform(xt)

array([[ 0.39223227, -1.56892908],
       [ 0.        ,  1.17669681],
       [-1.56892908,  0.        ],
       [ 1.17669681,  0.39223227]])

In [ ]:
MinMaxScaler().fit_transform(xt)

array([[0.71428571, 0.        ],
       [0.57142857, 1.        ],
       [0.        , 0.57142857],
       [1.        , 0.71428571]])

#### Function Transformer
    user defined function trnasformation

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
ft = FunctionTransformer(np.log2)

In [ ]:
ft.fit_transform(xt)

array([[2.80735492, 0.        ],
       [2.5849625 , 3.        ],
       [1.        , 2.32192809],
       [3.169925  , 2.5849625 ]])

#### Polynomial transformation

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
arr = np.array([[3,4]])
pf = PolynomialFeatures(degree=2)

In [ ]:
pf.fit_transform(arr)

array([[ 1.,  3.,  4.,  9., 12., 16.]])

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
ser = np.array([[0.1,0.3,0.2, 0.5, 6, 0.7, 0.9, 1.0]])
kbd = KBinsDiscretizer(strategy='uniform', encode='ordinal')